name: publish

on: workflow_dispatch

jobs:
  build_and_publish:
    name: 'Build and publish new version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # https://github.com/actions/checkout/issues/439
          fetch-depth: 0
          ref: master

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/

      - name: creating dir structure
        run: |
          mkdir WebView
          mkdir WebView/node_modules
          mkdir WebView/node_modules/@flowpub
          mkdir WebView/node_modules/@flowpub/content
          mkdir WebView/node_modules/@flowpub/core
          mkdir WebView/node_modules/@flowpub/css-pack
          mkdir WebView/node_modules/@flowpub/drm-module
          mkdir WebView/node_modules/@flowpub/glue-modules
          mkdir WebView/node_modules/@flowpub/glue-rpc
          mkdir WebView/node_modules/@flowpub/glue-shared
          mkdir WebView/node_modules/@flowpub/navigator
          mkdir WebView/node_modules/@flowpub/publication
          mkdir WebView/node_modules/@flowpub/renderer
          mkdir WebView/node_modules/@flowpub/webpub-model
          mkdir WebView/readium-css
      - name: copy files
        run: |
          cp -r packages               WebView
      - name: zip Runtime
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Runtime.zip'
          directory: 'WebView'
      - name: move Runtime.zip to root
        run: mv WebView/Runtime.zip ./
      - name: upload Runtime.zip
        uses: actions/upload-artifact@master
        with:
          name: Runtime.zip
          path: Runtime.zip

      # - name: npm ci
      #   run: |
      #     npm ci
      #   env:
      #     CI: true

      - name: npx lerna bootsrtap
        run: |
          npx lerna bootsrtap

      # https://github.com/lerna/lerna/issues/2162#issuecomment-657853895

      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
      - name: npm publish
        run: |
          npm run publish -- --yes
