name: publish

on: workflow_dispatch

jobs:
  build_and_publish:
    name: 'Build and publish new version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # https://github.com/actions/checkout/issues/439
          fetch-depth: 0
          ref: master

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/

      # - name: npm ci
      #   run: |
      #     npm ci
      #   env:
      #     CI: true

      # https://github.com/lerna/lerna/issues/2162#issuecomment-657853895

      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
      - name: npm publish
        run: |
          npm run publish -- --yes
